const constants = {
  ADD_TASK: 'ADD_TASK',
  START_TASK: 'START_TASK',
  STOP_TASK: 'STOP_TASK',
  SET_MY_TASK: 'SET_MY_TASK',

  INTERVAL_START: 'INTERVAL_START',
  INTERVAL_STOP: 'INTERVAL_STOP',
  INTERVAL_TIKTAK: 'INTERVAL_TIKTAK',

  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',

  INIT_STATE: 'INIT_STATE',
  INIT_USERS: 'INIT_USERS',
  INIT_TASKS: 'INIT_TASKS'
};
export default constants;
