const constants = {
  ADD_TASK: 'ADD_TASK',
  START_TASK: 'START_TASK',
  STOP_TASK: 'STOP_TASK',
  INTERVAL_START: 'INTERVAL_START',
  INTERVAL_STOP: 'INTERVAL_STOP',
  INTERVAL_TIKTAK: 'INTERVAL_TIKTAK'
};
export default constants;
